<a href="https://colab.research.google.com/github/Mhsm2012/car_prediction_ML/blob/main/markvoclustering.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
import numpy as np

In [15]:
MG = np.matrix([[0,1,1,0,0,0],[1,0,	1	,0,	0	,0],[1,	1	,0,	1	,0,	0],[0	,0	,1	,0	,1,	1],[0	,0,	0	,1,	0	,1],[0,	0	,0,	1,	1	,0]])

In [16]:
MG

matrix([[0, 1, 1, 0, 0, 0],
        [1, 0, 1, 0, 0, 0],
        [1, 1, 0, 1, 0, 0],
        [0, 0, 1, 0, 1, 1],
        [0, 0, 0, 1, 0, 1],
        [0, 0, 0, 1, 1, 0]])

In [17]:
M2g =np.dot(MG,MG)

In [18]:
M2g

matrix([[2, 1, 1, 1, 0, 0],
        [1, 2, 1, 1, 0, 0],
        [1, 1, 3, 0, 1, 1],
        [1, 1, 0, 3, 1, 1],
        [0, 0, 1, 1, 2, 1],
        [0, 0, 1, 1, 1, 2]])

In [19]:
identity_mat = np.identity(6)

In [20]:
identity_mat

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [21]:
mat_addition = np.add(MG,identity_mat)

In [22]:
mat_addition

matrix([[1., 1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0., 0.],
        [1., 1., 1., 1., 0., 0.],
        [0., 0., 1., 1., 1., 1.],
        [0., 0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1., 1.]])

In [24]:
MG2 = np.dot(mat_addition,mat_addition)

In [25]:
MG2

matrix([[3., 3., 3., 1., 0., 0.],
        [3., 3., 3., 1., 0., 0.],
        [3., 3., 4., 2., 1., 1.],
        [1., 1., 2., 4., 3., 3.],
        [0., 0., 1., 3., 3., 3.],
        [0., 0., 1., 3., 3., 3.]])

In [26]:
MG

matrix([[0, 1, 1, 0, 0, 0],
        [1, 0, 1, 0, 0, 0],
        [1, 1, 0, 1, 0, 0],
        [0, 0, 1, 0, 1, 1],
        [0, 0, 0, 1, 0, 1],
        [0, 0, 0, 1, 1, 0]])

In [27]:
MG_trans = MG/MG.sum(axis=0)

In [28]:
MG_trans

matrix([[0.        , 0.5       , 0.33333333, 0.        , 0.        ,
         0.        ],
        [0.5       , 0.        , 0.33333333, 0.        , 0.        ,
         0.        ],
        [0.5       , 0.5       , 0.        , 0.33333333, 0.        ,
         0.        ],
        [0.        , 0.        , 0.33333333, 0.        , 0.5       ,
         0.5       ],
        [0.        , 0.        , 0.        , 0.33333333, 0.        ,
         0.5       ],
        [0.        , 0.        , 0.        , 0.33333333, 0.5       ,
         0.        ]])

In [29]:
mg_t2=mat_addition/mat_addition.sum(axis=0)

In [30]:
mg_t2

matrix([[0.33333333, 0.33333333, 0.25      , 0.        , 0.        ,
         0.        ],
        [0.33333333, 0.33333333, 0.25      , 0.        , 0.        ,
         0.        ],
        [0.33333333, 0.33333333, 0.25      , 0.25      , 0.        ,
         0.        ],
        [0.        , 0.        , 0.25      , 0.25      , 0.33333333,
         0.33333333],
        [0.        , 0.        , 0.        , 0.25      , 0.33333333,
         0.33333333],
        [0.        , 0.        , 0.        , 0.25      , 0.33333333,
         0.33333333]])

In [37]:
aft_55 = np.linalg.matrix_power(mat_addition,2)

In [38]:
aft_55

matrix([[3., 3., 3., 1., 0., 0.],
        [3., 3., 3., 1., 0., 0.],
        [3., 3., 4., 2., 1., 1.],
        [1., 1., 2., 4., 3., 3.],
        [0., 0., 1., 3., 3., 3.],
        [0., 0., 1., 3., 3., 3.]])